---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket1:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Hello
          Value: World
  S3Bucket2:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Hello
          Value: World
  S3Bucket3:
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Hello
          Value: World